---
# tasks for webservers to run git clone on repo and run application
#- name: Apt | Update
#  apt:
#    update-cache: yes

- name: Synchronize | App and docker directories
  synchronize:
    src: app/app
    dest: /home/andurs/app

# --- This is a hack ---    
# - name: Copy | Private key for git repository
#   copy:
#     src: id_rsa
#     dest: /home/andurs/.ssh/id_rsa
#     mode: 0600
# - name: Git | Clone git repository
#   git:
#     repo: https://github.com/Andurshurrdurr/FlaskMask.git
#     dest: /home/andurs/app/
# #    accept_hostkey: yes
# #    force: yes
# #    recursive: no
# #    key_file: /home/andurs/.ssh/id_rsa

# - name: Shell | Run docker-compose
#   shell: docker-compose build
#   args:
#     chdir: /home/andurs/app/docker/
#   notify: docker-compose up
