FROM ubuntu
RUN apt-get update && apt-get -y install python python-pip python-dev build-essential
RUN apt-get -y install mosquitto
RUN apt-get -y install libmysqlclient-dev
RUN apt-get -y install python-mysqldb
RUN pip install -U pip
RUN pip install mysql-python
RUN pip install sqlalchemy
RUN pip install paho-mqtt
COPY ./MQTT /MQTT
CMD python -u /MQTT/main.py
