FROM tiangolo/uwsgi-nginx-flask:flask
MAINTAINER Anders L. Hurum <anders@almatek.no>
LABEL description="Deploys a flask webserver. See <serveraddress>:80/"
RUN apt-get update && apt-get -y install rlwrap sqlite3 socat python-mysqldb
RUN pip install -U pip
RUN pip install mysql-python
RUN pip install flask packaging oauth2client redis passlib flask-httpauth requests
RUN pip install sqlalchemy flask-sqlalchemy psycopg2 bleach
EXPOSE 80
COPY ./app /app
